<a href="https://colab.research.google.com/github/ScriptSherpa/python-and-ds/blob/main/iguru4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
# where () ---> used to return index number

arr=np.array([34,56,78,9,76,55,4,23,45,67])
res =np.where(arr>5)
print(res)
print(arr[res])

(array([0, 1, 2, 3, 4, 5, 7, 8, 9]),)
[34 56 78  9 76 55 23 45 67]


In [ ]:
#concatenate  used to combine two diifrent/1d-2d together
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [ ]:
# array_split(arrayname,splitvalue)
arr=np.array([1,2,3,4,5,6])
res=np.array_split(arr,3)
print(res)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
# sorting of an array
#sort()

arr=np.array([34,56,78,9,76,55,4,23,45,67])
print(np.sort(arr))# by default it will sort in asecending order
print(np.sort(arr)[::-1])# by default it will sort in desecending order

[ 4  9 23 34 45 55 56 67 76 78]
[78 76 67 56 55 45 34 23  9  4]


In [ ]:
# default data type i float and zero ()

#1d array
arr=np.zeros(9)
print(arr)

# 2d array
arr=np.zeros((3,3),dtype='i')
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
# ones () it will fill an array with 1s
#default data type is float

#1d array
arr=np.ones(9)
print(arr)

#2d array
arr=np.ones((3,3),dtype='i')
print(arr)


[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
#full(size,constantvalue)
# used to fill an array with constant value

x=np.full(9,121)
print(x)


SyntaxError: unmatched ')' (<ipython-input-12-8b0e27adcbd6>, line 6)

In [ ]:
x=np.full((3,4),24)
print(x)

[[24 24 24 24]
 [24 24 24 24]
 [24 24 24 24]]


In [ ]:
# sum()
print(np.sum(x))

288


In [ ]:
# numpy random module
from numpy import random
x=random.randint(10,20)
print(x)

19


In [ ]:
# rand() method gernerates a random float value b/w 0 and 1
x=random.rand()
print(x)

0.30123339628274914


In [ ]:
# 1D array
arr = random.randint(100, size=(5))
print(arr)

#2D array
arr1 = random.randint(100,120, size=(4,5))
print(arr1)

[16 53 27 12 76]
[[106 114 101 101 115]
 [113 111 110 103 101]
 [110 111 102 111 116]
 [117 104 104 103 108]]


In [ ]:
# numpy broadcasting
# should be of same dimensions
arr1 =np.array([1,2,3])
arr2=np.array([1,2,3])
arr=arr1+arr2
print(arr)

[2 4 6]
