<a href="https://colab.research.google.com/github/ScriptSherpa/python-and-ds/blob/main/iguru3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# copy()  and  view()
# in copy() if you make any changes in original array , it won't effect copied array
# and if you make any changes in copied array , it won't effect original array


import numpy as np


# view  if chnage in org and copied array it will chnage and updagte in both files

org_arr = np.array([10,23,45,67,89,76])
copied_arr=org_arr.view()
print(org_arr)
print(copied_arr)

copied_arr[1]=234
print('original array :' , org_arr)
print('copied array :' , copied_arr)

[10 23 45 67 89 76]
[10 23 45 67 89 76]
original array : [ 10 234  45  67  89  76]
copied array : [ 10 234  45  67  89  76]


In [7]:
# rshape()
#used to change the dimensions of an array

# convert 1d  into 2d
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.shape)

arr = arr.reshape(3,5)
print(arr)
print(arr.reshape)

(12,)


ValueError: cannot reshape array of size 12 into shape (3,5)

In [8]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])


arr = arr.reshape(-1)
print(arr)
print(arr.shape)

[1 2 3 4 5 6]
(6,)


In [11]:
# filter an array
arr = np.array([1,2,4,5,6,7,89,98,67])
newarr = arr>5
print(newarr) #boolean masking
print(arr[newarr])

[False False False False  True  True  True  True  True]
[ 6  7 89 98 67]


In [12]:
#modify elements using boolean indexing

arr = np.array([1,3,56,90,23,58,2,4,5,6,7,89,98,67])
print(arr)
copied_arr = arr.copy()
copied_arr[arr%2==0]=0
print(copied_arr)

[ 1  3 56 90 23 58  2  4  5  6  7 89 98 67]
[ 1  3  0  0 23  0  0  0  5  0  7 89  0 67]
