<a href="https://colab.research.google.com/github/ScriptSherpa/python-and-ds/blob/main/mis4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
array1=np.array([[3,4,56,7],[6,7,8,9]],dtype='int32')
print(array1)

[[ 3  4 56  7]
 [ 6  7  8  9]]


In [5]:
array1.shape


(2, 4)

In [9]:
array1.dtype

dtype('int32')

In [11]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [14]:
np.ones(6)

np.ones(6).dtype

dtype('float64')

In [15]:
np.empty((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
# prompt: array1

import numpy as np
print(array1[1,1])
print(array1[0,:])
print(array1[:,2])
array1[1,1] = 10
print(array1)
array2 = np.array([1,2,3,4,5])
print(array1.dtype)
print(array2.dtype)
array1 + 2
array1 * 2
array1 / 2
array3 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
array1 + array3
np.add(array1, array3)
np.subtract(array1,array3)
np.multiply(array1,array3)
array1.shape
array3.shape
array1 * array3
np.dot(array1,array3)
np.dot(array1,array3.T)
np.random.random((3,5))
np.random.rand(3,5)
np.random.randint(1,100,size=(3,5))
np.random.seed(1)
np.random.randint(1,100,size=(3,5))
np.random.seed(1)
np.random.randint(1,100,size=(3,5))
np.random.seed(1)
np.random.randint(1,100,size=(3,5))
np.random.seed(2)
np.random.randint(1,100,size=(3,5))
array1.max()
array1.min()
array1.mean()
array1.argmax()
array1.argmin()
np.where(array1 > 10)
array1[np.where(array1 > 10)]
array1[array1 > 10]
np.unique(array1)




In [16]:
array1

array([[ 3,  4, 56,  7],
       [ 6,  7,  8,  9]], dtype=int32)

In [18]:
#array1**array1
1/array1

array([[0.33333333, 0.25      , 0.01785714, 0.14285714],
       [0.16666667, 0.14285714, 0.125     , 0.11111111]])

In [21]:
# SLICING
array2=np.array([2,3,4,5,6,7,8,9])


In [22]:
arr=array2[4:6]
arr

array([6, 7])

In [24]:
arr[0]=9
arr


array([9, 7])

In [25]:
array2

array([2, 3, 4, 5, 9, 7, 8, 9])

In [27]:
ar3=np.array([[2,3,4],[5,6,7]])

In [29]:
#ar3.sum(axis=0)
ar3.sum(axis=1)

array([ 9, 18])