<a href="https://colab.research.google.com/github/ScriptSherpa/python-and-ds/blob/main/mis5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
array1=np.array([[3,4,56,7],[6,7,8,9]],dtype='int32')
print(array1)

[[ 3  4 56  7]
 [ 6  7  8  9]]


In [ ]:
array1.shape


(2, 4)

In [ ]:
array1.dtype

dtype('int32')

In [ ]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones(6)

np.ones(6).dtype

dtype('float64')

In [ ]:
np.empty((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
# prompt: array1

import numpy as np
print(array1[1,1])
print(array1[0,:])
print(array1[:,2])
array1[1,1] = 10
print(array1)
array2 = np.array([1,2,3,4,5])
print(array1.dtype)
print(array2.dtype)
array1 + 2
array1 * 2
array1 / 2
array3 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
array1 + array3
np.add(array1, array3)
np.subtract(array1,array3)
np.multiply(array1,array3)
array1.shape
array3.shape
array1 * array3
np.dot(array1,array3)
np.dot(array1,array3.T)
np.random.random((3,5))
np.random.rand(3,5)
np.random.randint(1,100,size=(3,5))
np.random.seed(1)
np.random.randint(1,100,size=(3,5))
np.random.seed(1)
np.random.randint(1,100,size=(3,5))
np.random.seed(1)
np.random.randint(1,100,size=(3,5))
np.random.seed(2)
np.random.randint(1,100,size=(3,5))
array1.max()
array1.min()
array1.mean()
array1.argmax()
array1.argmin()
np.where(array1 > 10)
array1[np.where(array1 > 10)]
array1[array1 > 10]
np.unique(array1)




7
[ 3  4 56  7]
[56  8]
[[ 3  4 56  7]
 [ 6 10  8  9]]
int32
int64


ValueError: operands could not be broadcast together with shapes (2,4) (2,5) 

In [ ]:
array1

In [ ]:
#array1**array1
1/array1

In [ ]:
# SLICING
array2=np.array([2,3,4,5,6,7,8,9])


In [ ]:
arr=array2[4:6]
arr

In [ ]:
arr[0]=9
arr


In [ ]:
array2

In [ ]:
ar3=np.array([[2,3,4],[5,6,7]])

In [ ]:
#ar3.sum(axis=0)
ar3.sum(axis=1)

NameError: name 'ar3' is not defined

In [ ]:
import numpy as np

a =np.array([[1,2,3],[4,5,6]])
b =np.array([[7,8,9],[10,11,12]])
a.sum(axis=0)

array([5, 7, 9])

In [ ]:
# transpose of matrix
# ar1.dot(ar2.transpose())
np.dot(a,b.transpose())
np.cross(a,b)

array([[-6, 12, -6],
       [-6, 12, -6]])

In [ ]:
c =np.array([[3,4,5,6,7],[6,8,75,3,4]])
#np.sort(c)
#np.sort(c,axis=0,kind='mergesort')
np.sort(c,axis=0,kind='quicksort')

array([[ 3,  4,  5,  3,  4],
       [ 6,  8, 75,  6,  7]])

In [ ]:
import numpy as np
array1=np.array([[3,4,56,7],[6,7,8,9]],dtype='int32')
print(array1)

a = np.arange(6)
a

[[ 3  4 56  7]
 [ 6  7  8  9]]


array([0, 1, 2, 3, 4, 5])

In [ ]:
b = np.array([1,2,11,345,4,5,6,7,8,9,6,5,4,3,2,1,12,34,455,67,89,87,65,43])
b.shape

(24,)

In [ ]:
#b =b.reshape(8,3)
#b

In [ ]:
np.argsort(b)


array([ 0, 15,  1, 14, 13,  4, 12, 11,  5, 10,  6,  7,  8,  9,  2, 16, 17,
       23, 22, 19, 21, 20,  3, 18])

In [ ]:
np.argmin(b)


0

In [ ]:
np.argmax(b)

18

In [ ]:
import pandas as pd
 df1 = pd.DataFrame([[3,4,56],[4,5,6],[7,8,9],[4,3,2]])
 df1

IndentationError: unexpected indent (<ipython-input-2-41891ade02fd>, line 2)

In [8]:
import pandas as pd
df=pd.DataFrame()
print(df)
import pandas as pd
df1 = pd.DataFrame([[3,4,56],[4,5,6],[7,8,9],[4,3,2]],columns=['A1','B1','C1'])
df1


Empty DataFrame
Columns: []
Index: []


A1  B1  C1
0   3   4  56
1   4   5   6
2   7   8   9
3   4   3   2

In [6]:
df1.head(2)

0  1   2
0  3  4  56
1  4  5   6

In [3]:
df.tail(1)

Empty DataFrame
Columns: []
Index: []